
version: 2

formats: [htmlzip]

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.7"

python:
  install:
    - requirements: requirements-docs.txt
    - method: pip
      path: .

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: false

